### ISSUE TITLE
Issue about translate

### ISSUE THREAD

**Issue by yrq3027** [prokia/deepHops#3]
Hi, after training, I run the translate.py to generate SMILES with followed instruction, However I met some bug. Can you give me some solutions?
python translate.py -condition_dim 768  -use_graph_embedding -arch after_encoding -with_3d_confomer -model /data/u1/projects/mget_3d/experiments/data40_tue/3d_gcn/models/model_step_9500.pt -gpu 0 -src data40_tue_3d/src-test.txt -cond data40_tue_3d/cond-test.txt -output /data/u1/projects/mget_3d/summary_tue/data40/after/9500/pred.txt -beam_size 10 -n_best 10 -batch_size 16 -replace_unk -max_length 200 -fast -use_protein40

Traceback (most recent call last):
  File "translate.py", line 100, in <module>
    main(opt)
  File "translate.py", line 72, in main
    opt = opt)
  File "/home/data/aidd/deepHops/deephop/onmt/translate/translator.py", line 257, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/data/aidd/deepHops/deephop/onmt/translate/translator.py", line 441, in translate_batch
    return_attention=self.replace_unk)
  File "/home/data/aidd/deepHops/deephop/onmt/translate/translator.py", line 581, in _fast_translate_batch
    [alive_seq.index_select(0, select_indices),
RuntimeError: expected scalar type Long but found Float
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[DEBUG/MainProcess] running the remaining "atexit" finalizers

**Comment by spacewalk012** [comment]
Hey @yrq3027, I tried using topk_ids.div(vocab_size).floor().long() but the model output is inconsistent with the results mentioned in the paper. How did you resolve it?

**Comment by yrq3027** [comment]
emmm, I can't remember exactly. Recently I did not working on small molecule
